# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and Deploy Logic App

env:
  LA_NAME: 'la-project-LOB1-001'

on:
  workflow_dispatch:
    # Trigger the workflow every time the build workflow ran to completion
  workflow_run:
    workflows:
      - Deploy Logic App Infrastructure
    types:
      - completed
  # Triggers when an environment file has been changed  
  push:
    paths:
      - "logic/**"
      - ".github/workflows/logicapp_deploy.yml"

jobs:
  logic_app_build: 
    name: Build 
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout
      uses: actions/checkout@v1
    - name: Package logic
      run: (cd logic; mkdir -p ../output; zip -r ../output/logic.zip .)
    - name: Upload app zip package
      uses: actions/upload-artifact@v2
      with:
        name: logic
        path: ./output/
        retention-days: 1 

  logic_app_deploy: 
    name: Deploy 
    runs-on: ubuntu-latest
    needs: [logic_app_build]
    environment: 
      name: Dev
    steps: 
    - name: Checkout
      uses: actions/checkout@v1    
    - name: Login via Az module
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
        enable-AzPSSession: true 
    - uses: actions/download-artifact@master
      with:
        name: logic
        path: ./output/
        
    - name: Get publish Profile
      id: publishprofile
      uses: azure/powershell@v1
      with:
        inlineScript: |
          $profile = Get-AzWebAppPublishingProfile `
              -ResourceGroupName ${{ secrets.RG_LA }} `
              -Name ${{ env.LA_NAME }}
          $profile = $profile.Replace("`r", "").Replace("`n", "")
          Write-Output "::set-output name=profile::$profile"
        azPSVersion: latest

    - name: Deploy to Azure Logic App
      uses: Azure/functions-action@v1.3.1
      id: la
      with:
        app-name: ${{secrets.RG_LA}}
        package: './output/logic.zip'
        publish-profile: ${{steps.publishprofile.outputs.profile}}

    - name: Swap parameter files 
      id: params
      uses: azure/powershell@v1
      with:
        inlineScript: |
          az functionapp deploy --resource-group ${{ secrets.RG_LA }} --name ${{ env.LA_NAME }} --src-path  logic/azure.parameters.json --type static --target-path parameters.json
        azPSVersion: latest




# ##############################################################################
# Github Actions workflow for Logic App deployment 
# ##############################################################################
name: Build and Deploy Logic App to multiple environments

env:
  LA_NAME: 'la-project-LOB1-001'

on:
  workflow_dispatch:

  # Trigger the workflow every time the build workflow ran to completion
  workflow_run:
    workflows:
      - Deploy Logic App Infrastructure
    types:
      - completed

  # Triggers when an environment file has been changed  
  push:
    branches:
      - main
    paths:
      - "logic/**"
      - ".github/workflows/logicapp_deploy.yml"

jobs:
  test:
    name: Test and lint
    uses: open-sauced/open-sauced/.github/workflows/development.yml@main

  docker:
    name: Build container
    runs-on: ubuntu-latest
    steps:
      - name: "☁️ checkout repository"
        uses: actions/checkout@v2

      - name: "🔧 setup buildx"
        uses: docker/setup-buildx-action@v1

  build:
    name: Build application
    runs-on: ubuntu-latest
    steps:
      - name: "☁️ checkout repository"
        uses: actions/checkout@v2

      - name: "🔧 setup node"
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 16

      - name: "🔧 install npm@latest"
        run: npm i -g npm@latest

  release:
    environment:
      name: production
      url: https://github.com/${{ github.repository }}/releases/tag/${{ steps.semantic-release.outputs.release-tag }}
    name: Semantic release
    needs:
      - test
      - docker
      - build
    runs-on: ubuntu-latest
    steps:
      - name: "☁️ checkout repository"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: "📂 download docker artifacts"
        uses: actions/download-artifact@v2
        with:
          name: docker
          path: /tmp

  cleanup:
    name: Cleanup actions
    needs:
      - release
    runs-on: ubuntu-latest
    steps:
      - name: "♻️ remove build artifacts"
        uses: geekyeggo/delete-artifact@v1
        with:
          name: |
            build
            docker
            diagram